# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosSiga',
            fields=[
                ('id_proyecto', models.AutoField(db_column='id_Proyecto', primary_key=True, serialize=False)),
                ('desc_proyecto', models.CharField(blank=True, db_column='desc_Proyecto', max_length=255, null=True)),
                ('cod_proyecto', models.CharField(blank=True, db_column='cod_Proyecto', max_length=4, null=True)),
                ('codi_Meta', models.CharField(blank=True, db_column='codi_Meta', max_length=4, null=True)),
                ('modalidad', models.CharField(blank=True, db_column='modalidad', max_length=2, null=True)),
                ('CODI_DEPE_TDE', models.CharField(blank=True, db_column='CODI_DEPE_TDE', max_length=4, null=True)),
                ('annio_meta', models.CharField(blank=True, db_column='annio_Meta', max_length=4, null=True)),
                ('objetivo', models.CharField(blank=True, db_column='objetivo', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'PROYECTOS_SIGA',
                'managed': True,
            },
        ),
    ]
