# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproyectosistema',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_PROYECTO', to='seguridad.MaeProyecto'),
        ),
    ]
