# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maeusuario',
            name='nom_completo',
            field=models.CharField(blank=True, db_column='NOMBRE_COMPLETO', max_length=250, null=True),
        ),
    ]
