# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maetipousuario',
            name='nombre_tipousuario',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
