# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_maeusuario_nom_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproyectosistema',
            name='id_proyecto',
            field=models.ForeignKey(db_column='ID_PROYECTO', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='seguridad.MaeProyecto'),
        ),
        migrations.AlterField(
            model_name='reproyectosistema',
            name='id_sistema',
            field=models.ForeignKey(db_column='ID_SISTEMA', on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='seguridad.MaeSistema'),
        ),
    ]
