# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_auto_20160823_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maesistema',
            name='des_sist',
            field=models.CharField(blank=True, db_column='DES_SIST', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maesistema',
            name='nom_sist',
            field=models.CharField(blank=True, db_column='NOM_SIST', max_length=50, null=True),
        ),
    ]
