# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_auto_20160823_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remenu',
            name='padre_id',
            field=models.ForeignKey(blank=True, db_column='PADRE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.ReMenu'),
        ),
    ]
