# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_maeusuario_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPermisosMenuChild',
            fields=[
                ('id_permisosusuario', models.IntegerField(db_column='ID_PERMISOSUSUARIO', primary_key=True, serialize=False)),
                ('id_menu', models.IntegerField(db_column='ID_MENU')),
                ('cod_permiso', models.CharField(db_column='COD_PERMISO', max_length=4)),
                ('nom_permiso', models.CharField(db_column='NOM_PERMISO', max_length=15)),
                ('des_rol', models.CharField(db_column='DES_ROL', max_length=50)),
                ('id_usuario', models.IntegerField(db_column='ID_USUARIO')),
            ],
            options={
                'db_table': 'permisos_menu_child',
                'managed': False,
            },
        ),
    ]
