# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_auto_20160823_2101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remenu',
            unique_together=set([]),
        ),
    ]
