# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_viewpermisosmenuchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='remenu',
            name='slug',
            field=models.CharField(blank=True, db_column='slug', max_length=100, null=True),
        ),
    ]
