# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_remenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproyectosistema',
            name='titulo_sistema_padre',
            field=models.CharField(blank=True, db_column='TITULO_SISTEMA_PADRE', max_length=50, null=True),
        ),
    ]
