# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_reproyectosistema_titulo_sistema_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='maeproyecto',
            name='cod_meta',
            field=models.CharField(blank=True, db_column='COD_META', max_length=8, null=True),
        ),
    ]
