# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_auto_20161013_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='maesistema',
            name='codigo_sist',
            field=models.CharField(blank=True, db_column='CODIGO_SISTEMA', max_length=20, null=True),
        ),
    ]
